
atoms = {
            "hydrogen": 1,
            "helium": 2,
            "lithium": 3,
            "beryllium": 4,
            "boron": 5,
            "carbon": 6,
            "nitrogen": 7,
            "oxygen": 8,
            "fluorine": 9,
            "neon": 10,
            "sodium": 11,
            "magnesium": 12,
            "aluminium": 13,
            "silicon": 14,
            "phosphorus": 15,
            "sulfur": 16,
            "chlorine": 17,
            "argon": 18,
            "potassium": 19,
            "calcium": 20,
            "scandium": 21,
            "titanium": 22,
            "vanadium": 23,
            "chromium": 24,
            "manganese": 25,
            "iron": 26,
            "cobalt": 27,
            "nickel": 28,
            "copper": 29,
            "zinc": 30,
            "gallium": 31,
            "germanium": 32,
            "arsenic": 33,
            "selenium": 34,
            "bromine": 35,
            "krypton": 36,
            "rubidium": 37,
            "strontium": 38,
            "yttrium": 39,
            "zirconium": 40,
            "niobium": 41,
            "molybdenum": 42,
            "technetium": 43,
            "ruthenium": 44,
            "rhodium": 45,
            "palladium": 46,
            "silver": 47,
            "cadmium": 48,
            "indium": 49,
            "tin": 50,
            "antimony": 51,
            "tellurium": 52,
            "iodine": 53,
            "xenon": 54,
            "cesium": 55,
            "barium": 56,
            "lanthanum": 57,
            "cerium": 58,
            "praseodymium": 59,
            "neodymium": 60,
            "promethium": 61,
            "samarium": 62,
            "europium": 63,
            "gadolinium": 64,
            "terbium": 65,
            "dysprosium": 66,
            "holmium": 67,
            "erbium": 68,
            "thulium": 69,
            "ytterbium": 70,
            "lutetium": 71,
            "hafnium": 72,
            "tantalum": 73,
            "tungsten": 74,
            "rhenium": 75,
            "osmium": 76,
            "iridium": 77,
            "platinum": 78,
            "gold": 79,
            "mercury": 80,
            "thallium": 81,
            "lead": 82,
            "bismuth": 83,
            "polonium": 84,
            "astatine": 85,
            "radon": 86,
            "francium": 87,
            "radium": 88,
            "actinium": 89,
            "thorium": 90,
            "protactinium": 91,
            "uranium": 92,
            "neptunium": 93,
            "plutonium": 94,
            "americium": 95,
            "curium": 96,
            "berkelium": 97,
            "californium": 98,
            "einsteinium": 99,
            "fermium": 100,
            "mendelevium": 101,
            "nobelium": 102,
            "lawrencium": 103,
            "rutherfordium": 104,
            "dubnium": 105,
            "seaborgium": 106,
            "bohrium": 107,
            "hassium": 108,
            "meitnerium": 109,
            "darmstadtium": 110,
            "roentgenium": 111,
            "copernicium": 112,
            "nihonium": 113,
            "flerovium": 114,
            "moscovium": 115,
            "livermorium": 116,
            "tennessine": 117,
            "oganesson": 118
            }
a={
            "H": 1.008,
            "He": 4.0026,
            "Li": 6.94,
            "Be": 9.0122,
            "B": 10.81,
            "C": 12.01,
            "N": 14.01,
            "O": 16.00,
            "F": 19.00,
            "Ne": 20.18,
            "Na": 22.99,
            "Mg": 24.31,
            "Al": 26.98,
            "Si": 28.09,
            "P": 30.97,
            "S": 32.06,
            "Cl": 35.45,
            "Ar": 39.95,
            "K": 39.10,
            "Ca": 40.08,
            "Sc": 44.96,
            "Ti": 47.87,
            "V": 50.94,
            "Cr": 52.00,
            "Mn": 54.94,
            "Fe": 55.85,
            "Co": 58.93,
            "Ni": 58.69,
            "Cu": 63.55,
            "Zn": 65.38,
            "Ga": 69.72,
            "Ge": 72.63,
            "As": 74.92,
            "Se": 78.97,
            "Br": 79.90,
            "Kr": 83.80,
            "Rb": 85.47,
            "Sr": 87.62,
            "Y": 88.91,
            "Zr": 91.22,
            "Nb": 92.91,
            "Mo": 95.95,
            "Tc": 98,
            "Ru": 101.07,
            "Rh": 102.91,
            "Pd": 106.42,
            "Ag": 107.87,
            "Cd": 112.41,
            "In": 114.82,
            "Sn": 118.71,
            "Sb": 121.76,
            "Te": 127.60,
            "I": 126.90,
            "Xe": 131.29,
            "Cs": 132.91,
            "Ba": 137.33,
            "La": 138.91,
            "Ce": 140.12,
            "Pr": 140.91,
            "Nd": 144.24,
            "Pm": 145,
            "Sm": 150.36,
            "Eu": 151.96,
            "Gd": 157.25,
            "Tb": 158.93,
            "Dy": 162.50,
            "Ho": 164.93,
            "Er": 167.26,
            "Tm": 168.93,
            "Yb": 173.05,
            "Lu": 174.97,
            "Hf": 178.49,
            "Ta": 180.95,
            "W": 183.84,
            "Re": 186.21,
            "Os": 190.23,
            "Ir": 192.22,
            "Pt": 195.08,
            "Au": 196.97,
            "Hg": 200.59,
            "Tl": 204.38,
            "Pb": 207.2,
            "Bi": 208.98,
            "Po": 209,
            "At": 210,
            "Rn": 222,
            "Fr": 223,
            "Ra": 226,
            "Ac": 227,
            "Th": 232.04,
            "Pa": 231.04,
            "U": 238.03,
            "Np": 237,
            "Pu": 244,
            "Am": 243,
            "Cm": 247,
            "Bk": 247,
            "Cf": 251,
            "Es": 252,
            "Fm": 257,
            "Md": 258,
            "No": 259,
            "Lr": 266,
            "Rf": 267,
            "Db": 268,
            "Sg": 269,
            "Bh": 270,
            "Hs": 277,
            "Mt": 278,
            "Ds": 281,
            "Rg": 282,
            "Cn": 285,
            "Nh": 286,
            "Fl": 289,
            "Mc": 290,
            "Lv": 293,
            "Ts": 294,
            "Og": 294
            }
Chemistry=input("what you want to know.\n*atomic number\n*mass\n*mass of compound\n")
if Chemistry=="atomic number":
    element=input("enter the name of atom.:").lower()
    if element in atoms:
            print(f"atomic number of {element.capitalize()} is {atoms[element]}")
     else:
            print("Please check your entered element.\n thankyou")
elif Chemistry=="mass":
        atom=input("enter the atom:")
    if atom in a:
            print(f"atomic mass of {atom} is {a[atom]}")
elif Chemistry=="mass of compound":
    def molmass(formula):
        total_mass = 0
        i = 0
        while i < len(formula):
            element=formula[i]
            i+=1
            if i < len(formula) and formula[i].islower():
                element+=formula[i]
                i+=1
            number=""
            while i < len(formula) and formula[i].isdigit():
                number += formula[i]
                i+=1
            count=int(number) if number else 1
            total_mass += a[element] * count
        return total_mass
    compound=input("enter the formula of the compound:")
    print("mollar mass = ", molmass(compound), "amu")
else:
    ("we did't understand")
